name: slang_flutter
description: Flutter support for slang. This library provides helpful Flutter API.
version: 4.7.0
repository: https://github.com/slang-i18n/slang
publish_to: none

environment:
  flutter: '>=3.19.0'
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Use a tight version to ensure that all features are available
  slang:
    path: ../slang

dev_dependencies:
  intl: any
  flutter_test:
    sdk: flutter
